version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: site-viaarto-dev
    volumes:
      - ./docs:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
